### ISSUE TITLE
setup: concealcursor= conceallevel=2 ?

### ISSUE THREAD

**Issue by blueyed** [norcalli/nvim-terminal.lua#2]
Currently it sets up `concealcursor=nv`, but not conceallevel.

I think it would be good to use `conceallevel=2` to actual do the concealing, but not concealcursor (too see the codes at the cursorline).
Otherwise e.g. `c-a` / `c-x` will not work easily etc, and it appears to make horizontal movement "slower" (it looks like h/l go by unconcealed character, requiring you to use them several times with colored letters next to each other).

**Comment by norcalli** [comment]
Right, I forgot that I set my own `conceallevel` and I was debating about the `concealcursor` because, to someone who doesn't understand, it does indeed look like it's going slower. I agree with your proposal.
